//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memento.Identity.Resources
{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class SharedResources
	{
		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal SharedResources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Memento.Identity.Resources.SharedResources", typeof(SharedResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The creation was completed successfully..
		/// </summary>
		public static string CONTROLLER_CREATE_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_CREATE_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The deletion was completed successfully..
		/// </summary>
		public static string CONTROLLER_DELETE_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_DELETE_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The listing was obtained successfully..
		/// </summary>
		public static string CONTROLLER_GET_ALL_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_GET_ALL_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The detail was obtained successfully..
		/// </summary>
		public static string CONTROLLER_GET_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_GET_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The update was completed successfully..
		/// </summary>
		public static string CONTROLLER_UPDATE_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_UPDATE_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The field &apos;{0}&apos; already exists..
		/// </summary>
		public static string ERROR_DUPLICATE_FIELD
		{
			get
			{
				return ResourceManager.GetString("ERROR_DUPLICATE_FIELD", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The field &apos;{0}&apos; is invalid..
		/// </summary>
		public static string ERROR_INVALID_FIELD
		{
			get
			{
				return ResourceManager.GetString("ERROR_INVALID_FIELD", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to An error occured while loading the page. Please try again later..
		/// </summary>
		public static string ERROR_LOADING
		{
			get
			{
				return ResourceManager.GetString("ERROR_LOADING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {0} does not exist..
		/// </summary>
		public static string ERROR_NOT_FOUND
		{
			get
			{
				return ResourceManager.GetString("ERROR_NOT_FOUND", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to An error unexpected error occurred. Please try again later..
		/// </summary>
		public static string ERROR_UNEXPECTED
		{
			get
			{
				return ResourceManager.GetString("ERROR_UNEXPECTED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role.
		/// </summary>
		public static string ROLE
		{
			get
			{
				return ResourceManager.GetString("ROLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Concurrency Stamp.
		/// </summary>
		public static string ROLE_CONCURRENCYSTAMP
		{
			get
			{
				return ResourceManager.GetString("ROLE_CONCURRENCYSTAMP", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string ROLE_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("ROLE_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string ROLE_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("ROLE_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enabled.
		/// </summary>
		public static string ROLE_ENABLED
		{
			get
			{
				return ResourceManager.GetString("ROLE_ENABLED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enabled.
		/// </summary>
		public static string ROLE_ENABLED_CHECKED
		{
			get
			{
				return ResourceManager.GetString("ROLE_ENABLED_CHECKED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Disabled.
		/// </summary>
		public static string ROLE_ENABLED_UNCHECKED
		{
			get
			{
				return ResourceManager.GetString("ROLE_ENABLED_UNCHECKED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string ROLE_ID
		{
			get
			{
				return ResourceManager.GetString("ROLE_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string ROLE_NAME
		{
			get
			{
				return ResourceManager.GetString("ROLE_NAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ascending.
		/// </summary>
		public static string ROLE_ORDER_ASCENDING
		{
			get
			{
				return ResourceManager.GetString("ROLE_ORDER_ASCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Descending.
		/// </summary>
		public static string ROLE_ORDER_DESCENDING
		{
			get
			{
				return ResourceManager.GetString("ROLE_ORDER_DESCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claims.
		/// </summary>
		public static string ROLE_ROLECLAIMS
		{
			get
			{
				return ResourceManager.GetString("ROLE_ROLECLAIMS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Users.
		/// </summary>
		public static string ROLE_ROLEUSERS
		{
			get
			{
				return ResourceManager.GetString("ROLE_ROLEUSERS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string ROLE_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("ROLE_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string ROLE_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("ROLE_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim.
		/// </summary>
		public static string ROLECLAIM
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim Type.
		/// </summary>
		public static string ROLECLAIM_CLAIMTYPE
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_CLAIMTYPE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim Value.
		/// </summary>
		public static string ROLECLAIM_CLAIMVALUE
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_CLAIMVALUE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string ROLECLAIM_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string ROLECLAIM_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string ROLECLAIM_ID
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role.
		/// </summary>
		public static string ROLECLAIM_ROLE
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_ROLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role Identifier.
		/// </summary>
		public static string ROLECLAIM_ROLEID
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_ROLEID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string ROLECLAIM_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string ROLECLAIM_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User.
		/// </summary>
		public static string USER
		{
			get
			{
				return ResourceManager.GetString("USER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Access Failed Count.
		/// </summary>
		public static string USER_ACCESSFAILEDCOUNT
		{
			get
			{
				return ResourceManager.GetString("USER_ACCESSFAILEDCOUNT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Concurrency Stamp.
		/// </summary>
		public static string USER_CONCURRENCYSTAMP
		{
			get
			{
				return ResourceManager.GetString("USER_CONCURRENCYSTAMP", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string USER_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("USER_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string USER_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("USER_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Email.
		/// </summary>
		public static string USER_EMAIL
		{
			get
			{
				return ResourceManager.GetString("USER_EMAIL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Email Confirmed.
		/// </summary>
		public static string USER_EMAILCONFIRMED
		{
			get
			{
				return ResourceManager.GetString("USER_EMAILCONFIRMED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enabled.
		/// </summary>
		public static string USER_ENABLED
		{
			get
			{
				return ResourceManager.GetString("USER_ENABLED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enabled.
		/// </summary>
		public static string USER_ENABLED_CHECKED
		{
			get
			{
				return ResourceManager.GetString("USER_ENABLED_CHECKED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Disabled.
		/// </summary>
		public static string USER_ENABLED_UNCHECKED
		{
			get
			{
				return ResourceManager.GetString("USER_ENABLED_UNCHECKED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string USER_ID
		{
			get
			{
				return ResourceManager.GetString("USER_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lockout Enabled.
		/// </summary>
		public static string USER_LOCKOUTENABLED
		{
			get
			{
				return ResourceManager.GetString("USER_LOCKOUTENABLED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lockout Ends At.
		/// </summary>
		public static string USER_LOCKOUTEND
		{
			get
			{
				return ResourceManager.GetString("USER_LOCKOUTEND", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ascending.
		/// </summary>
		public static string USER_ORDER_ASCENDING
		{
			get
			{
				return ResourceManager.GetString("USER_ORDER_ASCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Descending.
		/// </summary>
		public static string USER_ORDER_DESCENDING
		{
			get
			{
				return ResourceManager.GetString("USER_ORDER_DESCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Password Hash.
		/// </summary>
		public static string USER_PASSWORDHASH
		{
			get
			{
				return ResourceManager.GetString("USER_PASSWORDHASH", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Phone Number.
		/// </summary>
		public static string USER_PHONENUMBER
		{
			get
			{
				return ResourceManager.GetString("USER_PHONENUMBER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Phone Number Confirmed.
		/// </summary>
		public static string USER_PHONENUMBERCONFIRMED
		{
			get
			{
				return ResourceManager.GetString("USER_PHONENUMBERCONFIRMED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Password Hash.
		/// </summary>
		public static string USER_SECURITYSTAMP
		{
			get
			{
				return ResourceManager.GetString("USER_SECURITYSTAMP", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Two Factor Enabled.
		/// </summary>
		public static string USER_TWOFACTORENABLED
		{
			get
			{
				return ResourceManager.GetString("USER_TWOFACTORENABLED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string USER_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("USER_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string USER_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("USER_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claims.
		/// </summary>
		public static string USER_USERCLAIMS
		{
			get
			{
				return ResourceManager.GetString("USER_USERCLAIMS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Logins.
		/// </summary>
		public static string USER_USERLOGINS
		{
			get
			{
				return ResourceManager.GetString("USER_USERLOGINS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Username.
		/// </summary>
		public static string USER_USERNAME
		{
			get
			{
				return ResourceManager.GetString("USER_USERNAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Roles.
		/// </summary>
		public static string USER_USERROLES
		{
			get
			{
				return ResourceManager.GetString("USER_USERROLES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Tokens.
		/// </summary>
		public static string USER_USERTOKENS
		{
			get
			{
				return ResourceManager.GetString("USER_USERTOKENS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim.
		/// </summary>
		public static string USERCLAIM
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim Type.
		/// </summary>
		public static string USERCLAIM_CLAIMTYPE
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_CLAIMTYPE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim Value.
		/// </summary>
		public static string USERCLAIM_CLAIMVALUE
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_CLAIMVALUE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string USERCLAIM_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string USERCLAIM_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string USERCLAIM_ID
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string USERCLAIM_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string USERCLAIM_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User.
		/// </summary>
		public static string USERCLAIM_USER
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_USER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User Identifier.
		/// </summary>
		public static string USERCLAIM_USERID
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_USERID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Login.
		/// </summary>
		public static string USERLOGIN
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string USERLOGIN_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string USERLOGIN_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Provider.
		/// </summary>
		public static string USERLOGIN_LOGINPROVIDER
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_LOGINPROVIDER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Provider Name.
		/// </summary>
		public static string USERLOGIN_PROVIDERDISPLAYNAME
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_PROVIDERDISPLAYNAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Provider Key.
		/// </summary>
		public static string USERLOGIN_PROVIDERKEY
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_PROVIDERKEY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string USERLOGIN_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string USERLOGIN_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User.
		/// </summary>
		public static string USERLOGIN_USER
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_USER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User Identifier.
		/// </summary>
		public static string USERLOGIN_USERID
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_USERID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User Role.
		/// </summary>
		public static string USERROLE
		{
			get
			{
				return ResourceManager.GetString("USERROLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string USERROLE_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERROLE_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string USERROLE_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERROLE_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role.
		/// </summary>
		public static string USERROLE_ROLE
		{
			get
			{
				return ResourceManager.GetString("USERROLE_ROLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role Identifier.
		/// </summary>
		public static string USERROLE_ROLEID
		{
			get
			{
				return ResourceManager.GetString("USERROLE_ROLEID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string USERROLE_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERROLE_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string USERROLE_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERROLE_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User.
		/// </summary>
		public static string USERROLE_USER
		{
			get
			{
				return ResourceManager.GetString("USERROLE_USER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User Identifier.
		/// </summary>
		public static string USERROLE_USERID
		{
			get
			{
				return ResourceManager.GetString("USERROLE_USERID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Login.
		/// </summary>
		public static string USERTOKEN
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string USERTOKEN_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string USERTOKEN_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Provider.
		/// </summary>
		public static string USERTOKEN_LOGINPROVIDER
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_LOGINPROVIDER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string USERTOKEN_NAME
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_NAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string USERTOKEN_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string USERTOKEN_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User.
		/// </summary>
		public static string USERTOKEN_USER
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_USER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User Identifier.
		/// </summary>
		public static string USERTOKEN_USERID
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_USERID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Value.
		/// </summary>
		public static string USERTOKEN_VALUE
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_VALUE", resourceCulture);
			}
		}
	}
}
